### ISSUE TITLE
unable to download specs

### ISSUE THREAD

**Issue by Spongman** [oneM2M/Issues-Questions#2]
in Google Chrome Version 87.0.4280.88 (Official Build) (64-bit), the 'download' links on this page: https://www.onem2m.org/technical/published-drafts/release-2 result in

> Mixed Content: The site at 'https://www.onem2m.org/' was loaded over a secure connection, but the file at 'https://member.onem2m.org/Application/documentapp/downloadLatestRevision/default.aspx?docID=32574' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

**Comment by ankraft** [comment]
Thanks for reporting this. This should be fixed now. 
Could you please confirm that it is now working correctly on your side?

**Comment by Spongman** [comment]
yup. works great, thanks!
