### ISSUE TITLE
units for relative 'absRelTimestamp'

### ISSUE THREAD

**Issue by Spongman** [oneM2M/Issues-Questions#9]
it got changed to an `xs:long`, but ts-0004 still doesn't specify what the units are. seconds? milliseconds? fortnights?

**Comment by ankraft** [comment]
Thank you for noticing that. I added a change request in 2021 that was agreed but doesn't seem to have been copied into TS-0004. The CR number is SDS-2021-0190, and the agreed change is (in bold):

| XSD type name  | Type Name | Examples | Description |
|-|-|-|-|
|m2m:absRelTimestame | absolute or relative time stamp string |20141003T112032 (absolute time),or 3600000 (relative time) | defined as xs:union of m2m:timestamp and xs:long data types. **The unit for relative time is milliseconds.**  |

**Comment by Spongman** [comment]
thanks
